### ISSUE TITLE
Example cloud-config + cloud_properties options?

### ISSUE THREAD

**Issue by drnic** [oracle/bosh-oracle-cpi-release#2]
To help ppl use your CPI on Oracle Cloud, they might benefit from an example `bosh cloud-config` and a discussion of the [`cloud_properties` options](https://github.com/oracle/bosh-oracle-cpi/blob/master/action/cloud_properties.go)

Congrats to the team for so quickly writing a CPI and releasing it!

**Comment by dmutreja** [comment]
Thanks @drnic.  Yes, the examples are certainly a must. We the ops file and cloud-config for director and zookeeper hosted in our internal samples repos. We'll either get that open sourced too or add the samples here.  And yes, a doc or wiki explaining the properties is in order and I'll publish one shortly.

**Comment by drnic** [comment]
One idea might be to get an `oracle/` folder in https://github.com/cloudfoundry/bosh-deployment, as well as a simple test in its `test.sh`. Perhaps work with @cppforlife + team to help setup a test harness between their CI + an Oracle Cloud they can use.

**Comment by dmutreja** [comment]
cc @bitsarvi

**Comment by dmutreja** [comment]
@drnic we are working with @cppforlife + team on the CPI certification that'll allow us to push Oracle specific ops file under  https://github.com/cloudfoundry/bosh-deployment.   

Currently those ops files are under [bosh-deployment](https://github.com/oracle/bosh-oracle-cpi-release/tree/master/bosh-deployment) in this repo.  

Also, updated [README](https://github.com/oracle/bosh-oracle-cpi-release/blob/master/README.md) and added [Bosh Director Deployment Guide](https://github.com/oracle/bosh-oracle-cpi-release/blob/master/docs/deploy_director.md) that are hopefully helpful in the interim.

**Comment by dmutreja** [comment]
This issue was moved to cloudfoundry-incubator/bosh-oracle-cpi-release#3
